export const STREET_INPUT_CHANGED = 'STREET_INPUT_CHANGED';
export const CITY_INPUT_CHANGED = 'CITY_INPUT_CHANGED';
export const STATE_INPUT_CHANGED = 'STATE_INPUT_CHANGED';
export const ZIP_INPUT_CHANGED = 'ZIP_INPUT_CHANGED';

export const FETCHED_OFFICIALS = 'FETCHED_OFFICIALS';
export const OFFICIALS_LOOKUP_START = 'OFFICIALS_LOOKUP_START';
export const OFFICIALS_LOOKUP_SUCCESS = 'OFFICIALS_LOOKUP_SUCCESS';
