export const STREET_ADDRESS_CHANGED = 'STREET_ADDRESS_CHANGED';
export const CITY_CHANGED = 'CITY_CHANGED';
export const STATE_CHANGED = 'STATE_CHANGED';
export const ZIP_CODE_CHANGED = 'ZIP_CODE_CHANGED';
