export const STREET_INPUT_CHANGED = 'STREET_INPUT_CHANGED';
export const CITY_INPUT_CHANGED = 'CITY_INPUT_CHANGED';
export const STATE_INPUT_CHANGED = 'STATE_INPUT_CHANGED';
export const ZIP_INPUT_CHANGED = 'ZIP_INPUT_CHANGED';
